# Generated by Django 5.1.6 on 2025-03-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='emp_company',
            field=models.CharField(max_length=30),
        ),
    ]
